# Generated by Django 5.0 on 2026-06-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Severidade', models.IntegerField(help_text='Nível de severidade do acidente (1 a 4)')),
                ('Latitude_Inicial', models.FloatField(help_text='Latitude inicial do local do acidente')),
                ('Longitude_Inicial', models.FloatField(help_text='Longitude inicial do local do acidente')),
                ('Distancia_Milhas', models.FloatField(help_text='Distância da rodovia afetada pelo acidente (em milhas)')),
                ('Temperatura_F', models.FloatField(help_text='Temperatura em Fahrenheit')),
                ('Umidade_Percentual', models.FloatField(help_text='Umidade relativa do ar (%)')),
                ('Pressao_Polegadas', models.FloatField(help_text='Pressão atmosférica em polegadas de mercúrio')),
                ('Visibilidade_Milhas', models.FloatField(help_text='Visibilidade em milhas')),
                ('Velocidade_Vento_Mph', models.FloatField(help_text='Velocidade do vento em MPH')),
                ('Precipitacao_Polegadas', models.FloatField(help_text='Acúmulo de precipitação em polegadas')),
                ('Comodidade', models.BooleanField(default=False, help_text='Presença de comodidades/áreas de descanso')),
                ('Lombada', models.BooleanField(default=False, help_text='Presença de lombada física')),
                ('Cruzamento', models.BooleanField(default=False, help_text='Presença de cruzamento')),
                ('Preferencia', models.BooleanField(default=False, help_text='Sinalização de Dê a Preferência')),
                ('Juncao', models.BooleanField(default=False, help_text='Presença de entroncamento/junção')),
                ('Sem_Saida', models.BooleanField(default=False, help_text='Via sem saída')),
                ('Via_Ferrea', models.BooleanField(default=False, help_text='Proximidade de trilhos de trem')),
                ('Rotatoria', models.BooleanField(default=False, help_text='Presença de rotatória')),
                ('Estacao', models.BooleanField(default=False, help_text='Proximidade de estação de transporte público')),
                ('Pare', models.BooleanField(default=False, help_text='Sinalização de Pare (Stop)')),
                ('Redutor_Velocidade', models.BooleanField(default=False, help_text='Presença de redutores de velocidade')),
                ('Semaforo', models.BooleanField(default=False, help_text='Presença de semáforo')),
                ('Hora_do_Dia', models.IntegerField(help_text='Hora do dia em que ocorreu (0 a 23)')),
                ('Dia_da_Semana', models.IntegerField(help_text='Dia da semana (0 = Segunda, 6 = Domingo)')),
                ('Mes', models.IntegerField(help_text='Mês do ano (1 a 12)')),
                ('Horario_Pico', models.BooleanField(default=False, help_text='Flag indicando se ocorreu em horário de pico de trânsito')),
                ('Cluster_Espacial', models.IntegerField(help_text='ID do cluster geográfico (0 a 19)')),
            ],
            options={
                'verbose_name': 'Acidente',
                'verbose_name_plural': 'Acidentes',
                'indexes': [models.Index(fields=['Latitude_Inicial', 'Longitude_Inicial'], name='idx_coords'), models.Index(fields=['Severidade'], name='idx_severity')],
            },
        ),
    ]
